#!/usr/bin/env python3
"""Turn QCES-v6 evaluation receipts into paper tables and LaTeX macros.

No number in the manuscript is typed by hand.  This reads the fingerprinted
report JSONs and emits both a Markdown table set for review and a
``\\newcommand`` file for the manuscript, so a stale number cannot survive a
re-run: a missing report becomes a visible ``PENDING`` rather than an old value.
"""
# flake8: noqa: E402

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Mapping, Sequence

MODE_LABELS: Mapping[str, tuple[str, str]] = {
    "mixture_passthrough": ("Mixture, unchanged", "--"),
    "question_prompt__no_gate": ("Question as query", "--"),
    "energy_predicted__predicted_gate": ("Ours, energy reader", "--"),
    "predicted__no_gate": ("Ours, no gate", "--"),
    "predicted__predicted_gate": ("\\textbf{Ours (full)}", "--"),
    "predicted__best_effort": ("Ours, never silent", "--"),
    "oracle_inventory__planned_gate": ("Planner, given inventory", "inv."),
    "oracle_text__no_gate": ("Given labels, no gate", "lab."),
    "oracle_text__oracle_gate": ("Given labels and spans", "lab.+sp."),
}

MODE_ORDER = tuple(MODE_LABELS)

# Modes whose numbers the manuscript quotes inline through a macro.
MACRO_MODES = (
    "predicted__predicted_gate",
    "predicted__no_gate",
    "oracle_inventory__planned_gate",
    "oracle_text__oracle_gate",
    "question_prompt__no_gate",
)

SPLIT_LABELS: Mapping[str, str] = {
    "val": "val",
    "test_iid": "test-IID",
    "test_label_ood": "test-label-OOD",
    "test_compositional_ood": "test-comp-OOD",
}


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-root", type=Path, required=True)
    parser.add_argument("--parser-audit", type=Path, required=True)
    parser.add_argument("--markdown", type=Path, required=True)
    parser.add_argument("--macros", type=Path, required=True)
    parser.add_argument(
        "--latex",
        type=Path,
        help="Optional LaTeX tabular file for the manuscript to \\input.",
    )
    parser.add_argument(
        "--splits", nargs="+", default=list(SPLIT_LABELS)
    )
    return parser.parse_args(argv)


def load(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def number(value: Any, digits: int = 2) -> str:
    if value is None:
        return "--"
    return f"{float(value):.{digits}f}"


def macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def camel(text: str) -> str:
    return "".join(part.capitalize() for part in text.replace("-", "_").split("_"))


def mode_items(report: Mapping[str, Any], mode: str) -> list[Mapping[str, Any]]:
    return [item for item in report.get("items", []) if item.get("mode") == mode]


def no_evidence_recall(report: Mapping[str, Any], mode: str) -> float | None:
    """Pure recall on gold no-evidence records.

    Older pipeline summaries name answerability decision accuracy as
    ``planner_no_evidence_accuracy_↑``.  The paper uses no-evidence recall, so
    derive it directly from items.
    """

    negatives = [item for item in mode_items(report, mode) if item.get("no_evidence")]
    if not negatives:
        return None
    return sum(bool(item.get("planned_no_evidence")) for item in negatives) / len(negatives)


def answerability_decision_accuracy(report: Mapping[str, Any], mode: str) -> float | None:
    items = mode_items(report, mode)
    if not items:
        return None
    return sum(
        bool(item.get("planned_no_evidence")) == bool(item.get("no_evidence"))
        for item in items
    ) / len(items)


def latex_tables(
    pipelines: Mapping[str, Any],
    proposals: Mapping[str, Any],
    root: Path,
    splits: Sequence[str],
) -> str:
    """Emit the two manuscript tabulars, or a visible PENDING marker."""

    out: list[str] = [
        "% Generated by build_qces_v6_paper_tables.py. Do not edit by hand.",
        "",
    ]

    out += [
        "\\begin{table}[t]",
        "\\centering\\small\\setlength{\\tabcolsep}{3.2pt}",
        "\\caption{Evidence separation. $\\uparrow$ higher is better, "
        "$\\downarrow$ lower is better. `Reads' names the annotation a row "
        "consumes at inference; the deployable rows read none.}",
        "\\label{tab:main}",
        "\\begin{tabular}{llrrrrr}",
        "\\toprule",
        "Method & Reads & SD-SDRi $\\uparrow$ & Ans. $\\uparrow$ & "
        "NoEv. rec. $\\uparrow$ & Dec. $\\uparrow$ & IoU $\\uparrow$ \\\\",
        "\\midrule",
    ]
    report = pipelines.get("val")
    if report is None:
        out.append("\\multicolumn{7}{c}{\\textsc{pending}} \\\\")
    else:
        summaries = report["summaries_by_mode"]
        for mode in MODE_ORDER:
            values = summaries.get(mode)
            if values is None:
                continue
            name, access = MODE_LABELS[mode]
            if mode == "oracle_inventory__planned_gate":
                out.append("\\midrule")
            out.append(
                f"{name} & {access} & "
                f"{number(values['evidence_sd_sdri_answerable_mean_db_↑'])} & "
                f"{number(values['planner_answer_accuracy_↑'], 3)} & "
                f"{number(no_evidence_recall(report, mode), 3)} & "
                f"{number(answerability_decision_accuracy(report, mode), 3)} & "
                f"{number(values['planner_span_iou_mean_↑'], 3)} \\\\"
            )
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    out += [
        "\\begin{table}[t]",
        "\\centering\\small",
        "\\caption{Generalisation of the deployable system across splits, and "
        "the proposal stage that drives it.}",
        "\\label{tab:ood}",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Split & SD-SDRi $\\uparrow$ & Ans. $\\uparrow$ & Event $F_1$ $\\uparrow$ "
        "& \\#occ. acc. $\\uparrow$ \\\\",
        "\\midrule",
    ]
    any_row = False
    for split in splits:
        pipeline = pipelines.get(split)
        proposal = proposals.get(split)
        if pipeline is None:
            continue
        values = pipeline["summaries_by_mode"].get("predicted__predicted_gate")
        if values is None:
            continue
        reader = (
            proposal["readers"]["learned_head"] if proposal is not None else {}
        )
        any_row = True
        out.append(
            f"{SPLIT_LABELS.get(split, split)} & "
            f"{number(values['evidence_sd_sdri_answerable_mean_db_↑'])} & "
            f"{number(values['planner_answer_accuracy_↑'], 3)} & "
            f"{number(reader.get('event_f1_↑'), 3)} & "
            f"{number(reader.get('occurrence_count_accuracy_↑'), 3)} \\\\"
        )
    if not any_row:
        out.append("\\multicolumn{5}{c}{\\textsc{pending}} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(out)


def main(argv: Sequence[str] | None = None) -> None:
    args = parse_args(argv)
    root = args.results_root.resolve()

    pipelines = {
        split: load(root / f"pipeline_{split}" / "evaluation_report.json")
        for split in args.splits
    }
    proposals = {
        split: load(root / f"proposals_{split}.json") for split in args.splits
    }
    training = load(root / "proposal_head" / "training_report.json")
    audit = load(args.parser_audit.resolve())

    lines: list[str] = ["# QCES-v6 paper tables", ""]
    # Every macro the manuscript can reference is declared up front as a visible
    # PENDING.  A missing report then shows up in the PDF instead of breaking
    # the build or, worse, leaving a stale number behind.
    macro_values: dict[str, str] = {
        name: "\\textsc{pending}"
        for name in (
            "BenchmarkRecords",
            "ParserRelationAcc",
            "ParserQueryAcc",
            "EnergyPresenceAuc",
            "ClapPresenceAuc",
            "LearnedPresenceAuc",
            "OracleTextNoGate",
            "OracleTextOracleGate",
            "EnergyReaderAnswer",
            "EnergyReaderNoEv",
        )
    }
    for split in args.splits:
        for mode in MACRO_MODES:
            stem = camel(split) + camel(mode.replace("__", "_"))
            for suffix in (
                "SDRi", "Answer", "Median", "Positive", "NoEv", "Decision", "Iou", "Abstain"
            ):
                macro_values[stem + suffix] = "\\textsc{pending}"

    # ---- Table 1: benchmark composition and question understanding ----
    if audit is not None:
        lines += [
            "## Table 1 — benchmark and question understanding",
            "",
            "| Split | records | answerable | relation acc ↑ | query-field acc ↑ | "
            "planner answer acc ↑ (given inventory) | planner span exact ↑ |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
        for split, values in audit["splits"].items():
            lines.append(
                f"| {SPLIT_LABELS.get(split, split)} | {values['records']} | "
                f"{values['answerable_records']} | "
                f"{number(values['relation_accuracy_↑'], 4)} | "
                f"{number(values['query_field_accuracy_↑'], 4)} | "
                f"{number(values['planner_given_inventory_answer_accuracy_↑'], 4)} | "
                f"{number(values['planner_given_inventory_span_exact_rate_↑'], 4)} |"
            )
        lines.append("")
        total = sum(values["records"] for values in audit["splits"].values())
        macro_values["BenchmarkRecords"] = f"{total:,}"
        worst_relation = min(
            values["relation_accuracy_↑"] for values in audit["splits"].values()
        )
        worst_query = min(
            values["query_field_accuracy_↑"] for values in audit["splits"].values()
        )
        macro_values["ParserRelationAcc"] = number(worst_relation, 3)
        macro_values["ParserQueryAcc"] = number(worst_query, 3)

    # ---- Table 2: proposal quality ----
    if any(proposals.values()):
        lines += [
            "## Table 2 — proposal stage",
            "",
            "| Split | reader | presence AUC ↑ | frame F1 ↑ | event F1 ↑ | "
            "occurrence-count acc ↑ | onset MAE (s) ↓ | offset MAE (s) ↓ |",
            "|---|---|---:|---:|---:|---:|---:|---:|",
        ]
        for split in args.splits:
            report = proposals.get(split)
            if report is None:
                continue
            auc = report["label_presence_auc_↑"]
            for reader, values in report["readers"].items():
                presence = (
                    auc["learned_presence"]
                    if reader == "learned_head"
                    else auc["stem_energy_ratio"]
                )
                lines.append(
                    f"| {SPLIT_LABELS.get(split, split)} | {reader} | "
                    f"{number(presence, 3)} | {number(values['frame_f1_↑'], 3)} | "
                    f"{number(values['event_f1_↑'], 3)} | "
                    f"{number(values['occurrence_count_accuracy_↑'], 3)} | "
                    f"{number(values['onset_mae_seconds_↓'], 3)} | "
                    f"{number(values['offset_mae_seconds_↓'], 3)} |"
                )
        lines.append("")
        reference = proposals.get("val")
        if reference is not None:
            auc = reference["label_presence_auc_↑"]
            lines += [
                "### Presence signals on val (AUC ↑)",
                "",
                "| Signal | AUC ↑ |",
                "|---|---:|",
            ]
            for name, value in auc.items():
                lines.append(f"| {name} | {number(value, 3)} |")
            lines.append("")
            macro_values["EnergyPresenceAuc"] = number(auc["stem_energy_ratio"], 2)
            macro_values["ClapPresenceAuc"] = number(
                auc["clap_stem_self_similarity"], 2
            )
            macro_values["LearnedPresenceAuc"] = number(auc["learned_presence"], 2)

    # ---- Table 3: end-to-end separation ----
    for split in args.splits:
        report = pipelines.get(split)
        if report is None:
            continue
        lines += [
            f"## Table 3 — evidence separation on {SPLIT_LABELS.get(split, split)}",
            "",
            "| Method | annotation used | SD-SDRi ↑ | SI-SDRi ↑ | median SD-SDRi ↑ | "
            "positive rate ↑ | answer acc ↑ | no-evid recall ↑ | decision acc ↑ | span IoU ↑ | "
            "abstain on answerable ↓ |",
            "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
        summaries = report["summaries_by_mode"]
        for mode in MODE_ORDER:
            values = summaries.get(mode)
            if values is None:
                continue
            name, access = MODE_LABELS[mode]
            lines.append(
                f"| {name} | {access} | "
                f"{number(values['evidence_sd_sdri_answerable_mean_db_↑'])} | "
                f"{number(values['evidence_si_sdri_answerable_mean_db_↑'])} | "
                f"{number(values['evidence_sd_sdr_answerable_median_db_↑'])} | "
                f"{number(values['evidence_sd_sdri_answerable_positive_rate_↑'], 3)} | "
                f"{number(values['planner_answer_accuracy_↑'], 3)} | "
                f"{number(no_evidence_recall(report, mode), 3)} | "
                f"{number(answerability_decision_accuracy(report, mode), 3)} | "
                f"{number(values['planner_span_iou_mean_↑'], 3)} | "
                f"{number(values['planner_abstention_rate_on_answerable_↓'], 3)} |"
            )
        lines.append("")
        if split == "val":
            energy = summaries.get("energy_predicted__predicted_gate")
            if energy is not None:
                macro_values["EnergyReaderAnswer"] = number(
                    energy["planner_answer_accuracy_↑"], 3
                )
                macro_values["EnergyReaderNoEv"] = number(
                    no_evidence_recall(report, "energy_predicted__predicted_gate"), 3
                )
            for name, mode in (
                ("OracleTextNoGate", "oracle_text__no_gate"),
                ("OracleTextOracleGate", "oracle_text__oracle_gate"),
            ):
                values = summaries.get(mode)
                if values is not None:
                    macro_values[name] = number(
                        values["evidence_sd_sdri_answerable_mean_db_↑"]
                    )
        for mode in MACRO_MODES:
            values = summaries.get(mode)
            if values is None:
                continue
            stem = camel(split) + camel(mode.replace("__", "_"))
            macro_values[stem + "SDRi"] = number(
                values["evidence_sd_sdri_answerable_mean_db_↑"]
            )
            macro_values[stem + "Answer"] = number(
                values["planner_answer_accuracy_↑"], 3
            )
            macro_values[stem + "Median"] = number(
                values["evidence_sd_sdr_answerable_median_db_↑"]
            )
            macro_values[stem + "Positive"] = number(
                values["evidence_sd_sdri_answerable_positive_rate_↑"], 3
            )
            macro_values[stem + "NoEv"] = number(
                no_evidence_recall(report, mode), 3
            )
            macro_values[stem + "Decision"] = number(
                answerability_decision_accuracy(report, mode), 3
            )
            macro_values[stem + "Iou"] = number(
                values["planner_span_iou_mean_↑"], 3
            )
            macro_values[stem + "Abstain"] = number(
                values["planner_abstention_rate_on_answerable_↓"], 3
            )

    # ---- Table 4: feature and decoding ablations (validation split) ----
    ablation_names = ("no_clap", "no_clap_stem", "no_competition", "no_onset_split")
    ablation_titles = {
        "no_clap": "-- all audio--text similarity channels",
        "no_clap_stem": "-- stem$\\times$text similarity only",
        "no_competition": "-- cross-candidate competition channels",
        "no_onset_split": "-- onset split at decoding",
    }
    rows: list[str] = []
    full_pipeline = pipelines.get("val")
    full_proposals = proposals.get("val")
    if full_pipeline is not None and full_proposals is not None:
        summary = full_pipeline["summaries_by_mode"].get("predicted__predicted_gate")
        reader = full_proposals["readers"]["learned_head"]
        if summary is not None:
            rows.append(
                f"| full system | {number(summary['evidence_sd_sdri_answerable_mean_db_↑'])} | "
                f"{number(summary['planner_answer_accuracy_↑'], 3)} | "
                f"{number(no_evidence_recall(full_pipeline, 'predicted__predicted_gate'), 3)} | "
                f"{number(reader['event_f1_↑'], 3)} | "
                f"{number(reader['occurrence_count_accuracy_↑'], 3)} |"
            )
    for name in ablation_names:
        pipeline = load(
            root / f"pipeline_ablation_{name}" / "evaluation_report.json"
        )
        proposal = load(root / f"proposals_ablation_{name}.json")
        if pipeline is None or proposal is None:
            continue
        summary = pipeline["summaries_by_mode"].get("predicted__predicted_gate")
        reader = proposal["readers"]["learned_head"]
        if summary is None:
            continue
        rows.append(
            f"| {ablation_titles[name]} | "
            f"{number(summary['evidence_sd_sdri_answerable_mean_db_↑'])} | "
            f"{number(summary['planner_answer_accuracy_↑'], 3)} | "
            f"{number(no_evidence_recall(pipeline, 'predicted__predicted_gate'), 3)} | "
            f"{number(reader['event_f1_↑'], 3)} | "
            f"{number(reader['occurrence_count_accuracy_↑'], 3)} |"
        )
    if rows:
        lines += [
            "## Table 4 — ablations on val",
            "",
            "| Variant | SD-SDRi ↑ | answer acc ↑ | no-evid recall ↑ | event F1 ↑ | "
            "occurrence-count acc ↑ |",
            "|---|---:|---:|---:|---:|---:|",
            *rows,
            "",
        ]

    if training is not None:
        lines += [
            "## Proposal head training",
            "",
            f"- train units: `{training['train_units']}` from "
            f"`{training['train_questions']}` questions",
            f"- val units: `{training['val_units']}` from "
            f"`{training['val_questions']}` questions",
            f"- selected epoch: `{training['best']['epoch']}`, "
            f"threshold `{training['best']['val_threshold']}`",
            "- training-free energy reader (val, best threshold): "
            f"`{json.dumps(training['training_free_energy_reader'])}`",
            "- note: the legacy key `planner_no_evidence_accuracy_↑` in the "
            "training report is answerability decision accuracy; paper tables "
            "derive pure no-evidence recall directly from item-level records.",
            "",
        ]

    if args.latex is not None:
        args.latex.parent.mkdir(parents=True, exist_ok=True)
        args.latex.write_text(
            latex_tables(pipelines, proposals, root, args.splits), encoding="utf-8"
        )
        print(f"wrote {args.latex}")

    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text("\n".join(lines), encoding="utf-8")
    args.macros.parent.mkdir(parents=True, exist_ok=True)
    args.macros.write_text(
        "% Generated by build_qces_v6_paper_tables.py from fingerprinted receipts.\n"
        "% Do not edit by hand; re-run the script instead.\n\n"
        + "".join(macro(name, value) for name, value in sorted(macro_values.items())),
        encoding="utf-8",
    )
    print(f"wrote {args.markdown}")
    print(f"wrote {args.macros}")


if __name__ == "__main__":
    main()
